# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Flickr Search Test' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flickr Search Test

  target 'Flickr Search TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Flickr Search TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
